// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

import {ObjectMeta} from "../meta/v1";

export namespace secretsstore {
    export namespace v1alpha1 {
        /**
         * SecretProviderClassPodStatusStatus defines the observed state of SecretProviderClassPodStatus
         */
        export interface SecretProviderClassPodStatusStatusArgs {
            mounted?: pulumi.Input<boolean>;
            objects?: pulumi.Input<pulumi.Input<inputs.secretsstore.v1alpha1.SecretProviderClassPodStatusStatusObjectsArgs>[]>;
            podName?: pulumi.Input<string>;
            secretProviderClassName?: pulumi.Input<string>;
            targetPath?: pulumi.Input<string>;
        }

        /**
         * SecretProviderClassObject defines the object fetched from external secrets store
         */
        export interface SecretProviderClassPodStatusStatusObjectsArgs {
            id?: pulumi.Input<string>;
            version?: pulumi.Input<string>;
        }

        /**
         * SecretProviderClassSpec defines the desired state of SecretProviderClass
         */
        export interface SecretProviderClassSpecArgs {
            /**
             * Configuration for specific provider
             */
            parameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * Configuration for provider name
             */
            provider?: pulumi.Input<string>;
            secretObjects?: pulumi.Input<pulumi.Input<inputs.secretsstore.v1alpha1.SecretProviderClassSpecSecretObjectsArgs>[]>;
        }

        /**
         * SecretObject defines the desired state of synced K8s secret objects
         */
        export interface SecretProviderClassSpecSecretObjectsArgs {
            /**
             * annotations of k8s secret object
             */
            annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            data?: pulumi.Input<pulumi.Input<inputs.secretsstore.v1alpha1.SecretProviderClassSpecSecretObjectsDataArgs>[]>;
            /**
             * labels of K8s secret object
             */
            labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * name of the K8s secret object
             */
            secretName?: pulumi.Input<string>;
            /**
             * type of K8s secret object
             */
            type?: pulumi.Input<string>;
        }

        /**
         * SecretObjectData defines the desired state of synced K8s secret object data
         */
        export interface SecretProviderClassSpecSecretObjectsDataArgs {
            /**
             * data field to populate
             */
            key?: pulumi.Input<string>;
            /**
             * name of the object to sync
             */
            objectName?: pulumi.Input<string>;
        }

        /**
         * SecretProviderClassStatus defines the observed state of SecretProviderClass
         */
        export interface SecretProviderClassStatusArgs {
            byPod?: pulumi.Input<pulumi.Input<inputs.secretsstore.v1alpha1.SecretProviderClassStatusByPodArgs>[]>;
        }

        /**
         * ByPodStatus defines the state of SecretProviderClass as seen by an individual controller
         */
        export interface SecretProviderClassStatusByPodArgs {
            /**
             * id of the pod that wrote the status
             */
            id?: pulumi.Input<string>;
            /**
             * namespace of the pod that wrote the status
             */
            namespace?: pulumi.Input<string>;
        }
    }
}
