// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./secretProviderClass";
export * from "./secretProviderClassPodStatus";

// Import resources to register:
import { SecretProviderClass } from "./secretProviderClass";
import { SecretProviderClassPodStatus } from "./secretProviderClassPodStatus";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:secrets-store.csi.x-k8s.io/v1alpha1:SecretProviderClass":
                return new SecretProviderClass(name, <any>undefined, { urn })
            case "kubernetes:secrets-store.csi.x-k8s.io/v1alpha1:SecretProviderClassPodStatus":
                return new SecretProviderClassPodStatus(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "secrets-store.csi.x-k8s.io/v1alpha1", _module)
